name: three_players_web
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: taoyu1013 <yut1013@163e.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_forms: ^2.1.0
  angular_router: ^2.0.0-alpha
  angular_components: ^0.13.0
  http: ^ 0.12.0
  stream_transform: ^ 0.0.19


dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  test: ^1.6.0
